<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('transactions', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->onDelete('cascade');
            
            // Unique tracking ID generated by our system (e.g., TXN-8472948)
            $table->string('transaction_id')->unique(); 
            
            // 'credit' (adding money) or 'debit' (spending money at the club)
            $table->enum('type', ['credit', 'debit']); 
            
            $table->decimal('amount', 10, 2);
            
            // e.g., 'razorpay', 'cash', 'pos_terminal'
            $table->string('payment_method'); 
            
            // 'pending', 'completed', 'failed', 'cancelled'
            $table->string('status')->default('pending'); 
            
            // External reference (Razorpay Payment ID or Cash Receipt Number)
            $table->string('reference_id')->nullable(); 
            
            $table->string('description')->nullable(); // e.g., "Wallet Top-up via UPI"

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('transactions');
    }
};
