/// <reference types="nativewind/types" />

declare module 'react-native-razorpay';

declare global {
  namespace JSX {
    interface IntrinsicElements {
      'mock-camera': any;
    }
  }
}
// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.